### ISSUE TITLE
Login ohne Internet

### ISSUE THREAD

**Issue by motherboard1999** [Angestoepselt/reversy2#10]
Bitte ein Fallback einbauen, damit Logins auch ohne Internetverbindung möglich sind

**Comment by blitze299** [comment]
Wie soll das bei einem online Dienst funktionieren Chef?

**Comment by motherboard1999** [comment]
Wenn Google erreichbar ist: Nutze Firebase
Wenn Google nicht erreichbar ist: Nutze lokale Datenbank

**Comment by blitze299** [comment]
Das macht von der Definition her keinen Sinn sorry, wie soll das gehen?
