### ISSUE TITLE
BackEnd: Install Error

### ISSUE THREAD

**Issue by motherboard1999** [Angestoepselt/reversy2#5]
➜  backend git:(master) ✗ npm install

> fsevents@1.1.3 install /Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h:839:18:../../nan/nan.h :839:warning18: : warning: 'MakeCallback''MakeCallback' is deprecated:  Use isMakeCallback(...,  deprecated:async_context) Use MakeCallback(...,  async_context) [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return node::MakeCallback(    return node::MakeCallback(

                 ^                 ^

/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h::171171::11::  note: note: 'MakeCallback' has'MakeCallback' been  explicitlyhas  markedbeen deprecated  explicitlyhere
marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h20::88 :20:note : expandednote : from expandedmacro  from'NODE_DEPRECATED' macro
 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
    __attribute__((deprecated(message))) declarator                   ^

                   ^
In file included from In file included from ../fsevents.cc:../fsevents.cc6::
6:
../../nan/nan.h:854../../nan/nan.h::18:854 :18:warning : 'MakeCallback'warning : is deprecated:'MakeCallback' is deprecated:  UseUse  MakeCallback(...,MakeCallback(...,  async_context)async_context)  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return node::MakeCallback(    return node::MakeCallback(

                 ^                 ^

/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h::164164::11::  notenote: : 'MakeCallback''MakeCallback'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h::8888::2020::  notenote: : expandedexpanded  fromfrom  macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^                   ^

In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h../fsevents.cc::8696:
:18../../nan/nan.h::869 :18: warning: warning: 'MakeCallback' is'MakeCallback'  deprecated:is  Usedeprecated:  MakeCallback(...,Use  async_context)MakeCallback(...,  [-Wdeprecated-declarations]async_context)
[-Wdeprecated-declarations]
    return node::MakeCallback(
    return node::MakeCallback(                 ^

                 ^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:157/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h::1157:: 1: note: note'MakeCallback':  has'MakeCallback'  beenhas  explicitlybeen  markedexplicitly  deprecatedmarked  heredeprecated
here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h20::88 :20:note : expandednote : from expandedmacro  from'NODE_DEPRECATED' macro
 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^    __attribute__((deprecated(message))) declarator

                   ^
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h../../nan/nan.h::1478:147831:: 31: warning: warning'MakeCallback':  is deprecated: 'MakeCallback'Use  MakeCallback(...,is  async_context)deprecated: [-Wdeprecated-declarations] Use
 MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
    return scope.Escape(node::MakeCallback(/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h
:171                              ^:
1: note: /Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h'MakeCallback': 171has: 1been:  explicitly markednote : deprecated 'MakeCallback'here has
 been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.hNODE_DEPRECATED("Use MakeCallback(..., async_context)",:
88:^20
: note: /Users/f.helmerich/.node-gyp/10.8.0/include/node/node.hexpanded: 88from: 20macro:  'NODE_DEPRECATED'
note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings generated.
4 warnings generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
  SOLINK_MODULE(target) Release/fse.node
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/10.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

> fsevents@1.2.4 install /Users/f.helmerich/Git/reversy2/backend/node_modules/nodemon/node_modules/fsevents
> node install

  COPY /Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
[fsevents] Success: "/Users/f.helmerich/Git/reversy2/backend/node_modules/nodemon/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> phantomjs-prebuilt@2.1.16 install /Users/f.helmerich/Git/reversy2/backend/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/xc/81h3t1cx1n94pm10cl14vl4nnj060g/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/f.helmerich/Git/reversy2/backend/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/xc/81h3t1cx1n94pm10cl14vl4nnj060g/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1534490721843/phantomjs-2.1.1-macosx -> /Users/f.helmerich/Git/reversy2/backend/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/f.helmerich/Git/reversy2/backend/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> chromedriver@2.33.2 install /Users/f.helmerich/Git/reversy2/backend/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_mac64.zip
Saving to /var/folders/xc/81h3t1cx1n94pm10cl14vl4nnj060g/T/chromedriver/chromedriver_mac64.zip
Received 781K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3920K...
Received 4704K...
Received 5299K total.
Extracting zip contents
Copying to target path /Users/f.helmerich/Git/reversy2/backend/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /Users/f.helmerich/Git/reversy2/backend/node_modules/chromedriver/lib/chromedriver/chromedriver

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/f.helmerich/Git/reversy2/backend/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> bootstrap-vue@1.2.0 postinstall /Users/f.helmerich/Git/reversy2/backend/node_modules/bootstrap-vue
> opencollective postinstall || exit 0

                      Thanks for installing bootstrap-vue 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 160
                              Number of backers: 10
                               Annual budget: 456 $
                              Current balance: 456 $

       👉  Donate: https://opencollective.com/bootstrap-vue/donate

> nodemon@1.18.3 postinstall /Users/f.helmerich/Git/reversy2/backend/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1651 packages from 1783 contributors and audited 10615 packages in 44.512s
found 356 vulnerabilities (291 low, 43 moderate, 18 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
➜  backend git:(master) ✗ npm install > ~/Desktop/BackEnd.log
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
In file included from ../fsevents.cc:6:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
In file included from ../fsevents.cc:6:
../../nan/nan.h    return node::MakeCallback(:
854:                 ^18
: warning: 'MakeCallback' is deprecated: Use /Users/f.helmerich/.node-gyp/10.8.0/include/node/node.hMakeCallback(...,: 171async_context): 1[-Wdeprecated-declarations]:
note: 'MakeCallback' has been explicitly    return node::MakeCallback(
marked deprecated                 ^
here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:854:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitlyIn file included from  ../fsevents.ccmarked: 6deprecated:
 here../../nan/nan.h:
869:18: warning: 'MakeCallback' is deprecated: UseNODE_DEPRECATED("Use MakeCallback(..., async_context)",
MakeCallback(..., async_context)^
[-Wdeprecated-declarations]
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:20:     return node::MakeCallback(
note                 ^:
expanded from macro/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h :'NODE_DEPRECATED'157:
1: note: 'MakeCallback' has been explicitly marked     __attribute__((deprecated(message))) declaratordeprecated
 here                   ^

NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:869:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1478:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1478:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/f.helmerich/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings generated.
4 warnings generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/f.helmerich/Git/reversy2/backend/node_modules/fsevents
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by blitze299** [comment]
fixed with new commit "fixed #5"
retry npm install
